server:
  port: 8080
spring:
  application:
    name: "ms-auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: ms_auth
    schema: public
    username: ms_auth
    password: ms_auth

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG

